# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['web_ui.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'gradio',
        'gradio.routes',
        'gradio.templates',
        'gradio.components',
        'gradio.blocks',
        'gradio.events',
        'gradio.helpers',
        'gradio.utils',
        'websockets',
        'websockets.client',
        'websockets.server',
        'websockets.legacy',
        'eth_account',
        'eth_account.account',
        'eth_account.messages',
        'eth_account.signers.local',
        'nacl.signing',
        'nacl.encoding',
        'httpx',
        'yaml',
        'plotly',
        'plotly.graph_objects',
        'pynacl',
        'eth_keys',
        'eth_utils',
        'eth_abi',
        'eth_hash',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='StandXMakerBot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
